import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../pagecomponents/Header";
import { CartProvider } from "@/context/CartContext";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={montserrat.className}>
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
