import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../pagecomponents/Header";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={montserrat.className}>
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
